SRombauts/SQLiteCpp

CMakeLists.txt
biicode.conf

I just added biicode support for your library,  it's a biicode.conf file and unobtrusive changes in CMakeLists.txt
I can also add an appveyor CI file to build it in Windows if you're interested. Many Thanks,
Maria

added biicode support

---

sqlite3/README.txt
sqlite3/sqlite3.h

Updated to sqlite v3.8.8.3
Previous was v3.8.8.2 but I just saw v3.8.8.3 was out so I went with the latest one

sqlite v3.8.8.3.

---

CMakeLists.txt
README.md
biicode.conf

Added README badge for biicode
Minor updates on CMakeLists.txt and biicode.conf file

improved biicode support

---

include/SQLiteCpp/Statement.h
src/Statement.cpp

add method `Column getColumn(const char* aName);` in Statement.h

Fix issue: Column by name #23

---

src/Database.cpp

A simple trick a have a nice build, without warning

Removed a warning in release build with Visual Studio

---

CMakeLists.txt
include/SQLiteCpp/Backup.h
src/Backup.cpp
tests/Backup_test.cpp

Add SQLite::Backup class as a RAII encapsulation of SQLite Database Backup

Support backup of DB file

---

.travis.yml

- multiple versions of gcc (default which is 4.8, 4.9, 5, 6)
- multiple versions of c++ standard ( 03, 11, 14, 1z)
- multiple versions of clang(default which is 3.5, 3.8)
- os x
see this test build: [https://travis-ci.org/pauldreik/SQLiteCpp/builds/140468462](url)

build with several compilers

---

include/SQLiteCpp/Database.h
src/Database.cpp
tests/Database_test.cpp

No advanced functionality, but one can open encrypted databases. requires you to have an external SQLite library that supports encryption.

Added ability to open encrypted databases.

---

CMakeLists.txt

This error message suggests incorrect git commands to init and update the required submodule/s. This PR corrects the suggestions.

Fix error message regarding git submodule init/update.

---

sqlite3/sqlite3.h

Updated SQlite to 3.27.1 to be on newest level

Updated SQlite to 3.27.1

---

include/SQLiteCpp/Utils.h

Fix problem with MSVC 19

---

CMakeLists.txt

Added support of packaged GTest for running unit tests with fallback to bundled version if not found.

Added support of packaged GTest for running unit tests

---

include/SQLiteCpp/Database.h
src/Database.cpp
tests/Database_test.cpp

using an example from
https://stackoverflow.com/a/8283265/1163698 How can I create a user-defined function in SQLite?

Add unit test for Database::createFunction()

---

examples/example1/main.cpp

Added example usage of getHeaderInfo() and print statements to show values.

Added example for getHeaderInfo()

---

CMakeLists.txt

Install cmake files into same directory

---

CMakeLists.txt

Fixed installation on other than Ubuntu distributions.

Fixed installation on other than Ubuntu distributions

---

package.xml

This pull request addresses #336.

Add catkin configuration

---

include/SQLiteCpp/Database.h

fix compilation issues earlier than iOS 13

---

.travis.yml
README.md
appveyor.yml
build.bat

Update documents about supported platforms

Add Visual Studio 2022 to AppVeyor CI/CD

---

subprojects/sqlite3.wrap

as the title says update the SQLite default version to 3.40.0

[meson] Update SQLite from 3.39.3 to 3.40.0

---

.github/workflows/meson.yaml
meson.build

PR that completes #403, adding the base meson CI pipeline

Create Meson CI

---

meson.build

Sets the meson package version to 3.3.0

Set Meson version to 3.3.0

---

.github/workflows/cmake.yml

To test more versions of compilers

Use explicit versions of Ubuntu images instead of latest

---

meson.build

fix compilation with newer gtest
