SRombauts/SQLiteCpp

- src/Database.cpp
mpSQLite is free'd with sqlite3_close. It's no more accesible.
Fixes: #48
> Use sqlite_errstr instead of sqlite3_errmsg

- include/SQLiteCpp/Database.h
- src/Database.cpp
I have added this to the loadExtension to Database class as preferred.
It passes all your existing unit tests, but doesn't have an explicit unit test, since this would require a dummy module to be added to the source base, which I didn't think was a good idea!
I have however tested against my application and it successfully loads and integrates a module into SQLite3.
> Added support for extension loading

- src/Database.cpp
SQLite extension loading feature can be disabled by defining [SQLITE_OMIT_LOAD_EXTENSION preprocessor macro](http://sqlite.org/compile.html#omitfeatures). If anyone defines SQLITE_OMIT_LOAD_EXTENSION, then compilation of Database.cpp fails with undefined external symbol. Database::loadExtension function needs conditional compile-time check for successful compilation in such environment.
> Added conditional support for extension loading

- include/SQLiteCpp/Column.h
I have changed `#if` condition masking `Column::operator std::string`, because a problem that implicit conversion to `std::string` does not work if there are both `operator std::string` and `operator const char *` is fixed from Visual C++ 2015.
The condition became more generic to support "standard" compilers not defining `__GNUC__`.
> Fix implicit conversion to std::string of Column class for Visual C++ 2015

- include/SQLiteCpp/Database.h
- include/SQLiteCpp/Exception.h
- include/SQLiteCpp/Statement.h
- src/Backup.cpp
- src/Database.cpp
- src/Statement.cpp
Added new constructor to Exception that takes sqlite3* pointer, allowing for getting more information out (sqlite3_errmsg). Makes it much easier to debug syntax errors in prepared statements, for example.
Also implements suggestion from #62 (storing error code).
> Better exception messages when statements fail

- CMakeLists.txt
- Doxyfile
- examples/example1/main.cpp
- include/SQLiteCpp/VariadicBind.h
- tests/VariadicBind_test.cpp
This gives the possibility to let the compiler generate the index argument in `Statement::bind()` automatically at compile time, instead of manually invoking bind.
Instead of
`SQLite::Statement stmt("SELECT * FROM MyTable WHERE colA>? && colB=? && colC<?");
stmt.bind(1,a);
stmt.bind(2,b);
stmt.bind(3,c);
`
one can write
`SQLite::bind(stmt,a,b,c);`
Note that this is implemented as a free function. It could be provided as a member function of `SQLite::Statement` instead, under a different name than bind in order not to clash with the existing `SQLite::Statement::bind()` overloads.
This requires c++14. Tested on gcc 5.3.1 on GNU/Linux.
> Variadic bind convenience function

- CMakeLists.txt
I'm adding SQLiteCpp to my project with CMake, using `add_subdirectory`.
The problem I found is that I need to manually add the path to the public header files (SQLiteCpp/include/ and SQLiteCpp/sqlite3), since they are not propagated automatically.
This PR add the `target_include_directories` so that the projects that include SQLiteCpp don't need to include the path to the public header files manually.
> Automatically propagate public headers to other projects with CMake

- include/SQLiteCpp/Statement.h
- src/Statement.cpp
- tests/Statement_test.cpp
While using the library I wanted to check is a column is null, but only found a method that allow to check it by index, so I added one that is similar but check by the column name.
I have also added the tests to it.
> Add option to check if column is null by name

- include/SQLiteCpp/Exception.h
- src/Exception.cpp
getErrorCode() and getExtendedErrorCode()'s implementations were
accidentally declared as inline in the .cpp file. This causes the
compiler to not generate any code for them, resulting in link errors
when a client calls them. (Observed compiling with Clang.)
Fixed by moving the implementations into the header, where they need to
be if they're inline.
> Fixed link errors calling Exception::getErrorCode()

- include/SQLiteCpp/Database.h
- src/Database.cpp
Fixes clang warning on Database.h:48: "'const' type qualifier on return type has no effect" and Database.cpp:44: "'const' type qualifier on return type has no effect"
> Redundant const specifier removed

- include/SQLiteCpp/Column.h
- include/SQLiteCpp/Statement.h
- tests/Statement_test.cpp
Added a template function that allows you to retrieve all columns (or first N columns) of a row as an object. Extremely convenient when working with a table that has a large number of columns. Instead of having to do:
int i0 = query.getColumn(0);
int i1 = query.getColumn(1);
...
int i39 = query.getColumn(39);
then passing all those temporary variables into a constructor, you can do:
auto i = query.getColumns<MyClass, 40>();
where MyClass has a constructor that takes 40 arguments that are convertible from a Column object.
> Added convenience functions for constructing objects from a row

- CMakeLists.txt
Currently, use of the library is quite cumbersome for us because it's lacking an install step.
This PR ensures that `make install` works correctly, and that users can reliably find it using `find_package` after `make install` has completed without any additional files or work.
> Add install step

- cpplint.py
Smallest fix to let cpplint.py work on python2 and 3
FIxes #99
> Make cpplint.py Python-3 compatible

- CMakeLists.txt
Now there is no need to link each target ot both libs
> linked SQLiteCpp to sqlite3

- CMakeLists.txt
- include/SQLiteCpp/Exception.h
- src/Exception.cpp
- tests/Exception_test.cpp
Hi,
subclasses of std::exception should have an assignment operator.
I've added test cases to ensure that such operator behaves correctly.
I've also added two constructor that takes const char* instead of const std::string& in order to avoid a possible allocation (in c++11) when creating the exception object.
> Enhance sqlite exception

- src/Database.cpp
This cleans up warnings observed under MSVC 15 and Clang (trunk). The latter had warnings with SQLITE_OMIT_LOAD_EXTENSION defined.
> Warning cleanup under MSVC and Clang

- src/Column.cpp
- tests/Column_test.cpp
Hello,
std::ostream& operator<<(std::ostream& aStream, const Column& aColumn) does not handle correctly content with an embedded '\0'.
I've also added a test case with a std::string.
Best regards
Federico
> Ensure that operator<< correctly prints strings with embedded '\0'

- include/SQLiteCpp/Column.h
- include/SQLiteCpp/Database.h
- src/Column.cpp
- src/Database.cpp
Hi,
there are a couple of method marked as noexcept, but in reality they may throw an exception.
The first method is Column::getString, since std::string needs to allocate memory, the constructor may fail and throw an exception
The second method is Database::setBusyTimeout, internally if the operation fails an exception is thrown.
I was going to remove the noexcept specifier from the destructors, since they are all noexcept if not stated otherwise, but maybe you preferred to state it explicitely, and since it does not make any difference from the language perspective, I leaved them.
> Remove noexcept

- include/SQLiteCpp/Backup.h
- include/SQLiteCpp/Column.h
- include/SQLiteCpp/Database.h
- include/SQLiteCpp/Statement.h
- include/SQLiteCpp/Transaction.h
- src/Backup.cpp
- src/Column.cpp
- src/Database.cpp
- src/Statement.cpp
- src/Transaction.cpp
This is a pull request for "cleaning" the destructors.
I've removed the noexcept identifier since it is unnecessary.
Some destructor are empty, I leaved them since most where commented.
I've noticed that they are all declared virtual, but there are no virtual method in any class or any subclass. 
Is there a reason? Otherwise we could also remove the virtual identifier.
> Remove unnecessary noexcept identifier from destructors

- include/SQLiteCpp/Backup.h
- include/SQLiteCpp/Column.h
- include/SQLiteCpp/Database.h
- include/SQLiteCpp/Statement.h
- include/SQLiteCpp/Transaction.h
As stated in https://github.com/SRombauts/SQLiteCpp/pull/139, virtual destructors have (currently) no use case
> Remove virtual destructor since there are no virtual methods or subclasses

- include/SQLiteCpp/Statement.h
- src/Statement.cpp
- tests/Statement_test.cpp
> Added tryExecuteStep and tryReset

- sqlite3/sqlite3.h
- tests/Statement_test.cpp
* Updated sqlite3/sqlite3.h and sqlite3/sqlite3.c
* Updated test Statment.invalid since error message has changed.
> updated sqlite3 to version 3.20.1

- include/SQLiteCpp/Statement.h
- tests/Statement_test.cpp
a3160dcfc2f80f692f3477a67c202ff87f75fa5a fixed this for bind by index
This PR just applies the same fix to the named functions.
> Allows long int for bind when used with name

- README.md
adding only SQLiteCpp to target_link_libraries() was not enough for me under ubuntu 16.04. 
there fore added cmake instructions in more detail.
> more cmake instructions for linux

- CMakeLists.txt
- tests/Database_test.cpp
- Added backwards compatibility with older CMake-versions. 
- Fixed a problem with the constantly failing encryption tests
There are quite a few non-sense commit messages, please squash-merge to master and write a single meaningful commit message.
> CMake compatibility

- include/SQLiteCpp/Database.h
This makes it possible to e.g. return Databases from functions. Gated behind a __cplusplus >= 201103L check for compatibility with older C++ versions. Defined inline due to its triviality and in order to avoid having to do the same preprocessor dance in two places.
Despite setting mpSQLite to null, there is no need to change the destructor, as sqlite3_close handles null pointers for us.
> Add a move constructor to Database

- .gitignore
- CMakeLists.txt
- include/SQLiteCpp/ExecuteMany.h
- include/SQLiteCpp/VariadicBind.h
- tests/ExecuteMany_test.cpp
- tests/VariadicBind_test.cpp
added the option to use a tuple with values to bind.
I will use this to implement executeMany as described in  #24, so it will be possible to pass multiple tuples
I only created this PR, so the CI already tests this, since I still need to implement executemany and add some tests
> add tuple bind

- include/SQLiteCpp/Statement.h
- src/Statement.cpp
- tests/Statement_test.cpp
- it returns a UTF-8 string containing the SQL text of prepared statement with
bound parameters expanded
> Add Statement::getExtendedSQL()

- include/SQLiteCpp/Database.h
- src/Database.cpp
- tests/Database_test.cpp
- it is possible to easily backup/restore a live DB via the
sqlite3_backup_init() API
- https://www.sqlite.org/backup.html
- https://www.sqlite.org/c3ref/backup_finish.html#sqlite3backupinit
> Implement Database::backup()

- sqlite3/CMakeLists.txt
Disables cast-function-type warning which is available in gcc 8.0 and greater.
> Disable cast-function-type warning when building internal sqlite

- CMakeLists.txt
Most of GNU/Linux distributions require SOVERSION field of shared library to be set.
You should bump SOVERSION every time you draft a new release with breaking API changes.
> Added SOVERSION field for shared library

- CMakeLists.txt
Explicitly find and link against system sqlite library when built with `-SQLITECPP_INTERNAL_SQLITE=OFF`.
This will fix -as-needed linker issue:
```text
sqlitecpp.x86_64: W: undefined-non-weak-symbol /usr/lib64/libSQLiteCpp.so.0
sqlite3_column_text
sqlitecpp.x86_64: W: undefined-non-weak-symbol /usr/lib64/libSQLiteCpp.so.0
sqlite3_close
sqlitecpp.x86_64: W: undefined-non-weak-symbol /usr/lib64/libSQLiteCpp.so.0
sqlite3_column_int
sqlitecpp.x86_64: W: undefined-non-weak-symbol /usr/lib64/libSQLiteCpp.so.0
sqlite3_reset
sqlitecpp.x86_64: W: undefined-non-weak-symbol /usr/lib64/libSQLiteCpp.so.0
sqlite3_bind_int
sqlitecpp.x86_64: W: undefined-non-weak-symbol /usr/lib64/libSQLiteCpp.so.0
sqlite3_total_changes
sqlitecpp.x86_64: W: undefined-non-weak-symbol /usr/lib64/libSQLiteCpp.so.0 …
```
> Explicitly find and link against system sqlite library

- include/SQLiteCpp/Database.h
- src/Database.cpp
- tests/Database_test.cpp
Added header parsing functionality via a `getHeaderInfo()` function. This function reads the first 100 bytes of a SQLite database file and attempts to reconstruct byte groups into the specific header fields within a Header object. Also added tests to demonstrate updating header values via PRAGMA and verifying updated / default header values.
> Added SQLite header parsing functionality and associated tests

- .editorconfig
- .travis.yml
- CHANGELOG.md
- CMakeLists.txt
- README.md
- TODO.txt
- build.sh
- include/SQLiteCpp/Database.h
- src/Database.cpp
- tests/Backup_test.cpp
- tests/Database_test.cpp
I found a minor issue in Unit Tests using Valgrind default memcheck tool, this need to be automated from now on.
> Run Valgrind memcheck on Travis CI

- .travis.yml
Manual execution of travisci_build_coverity_scan.sh as a workaround for not building on every job of the build matrix
> Re-enable Coverity static analysis

- .travis.yml
- CMakeLists.txt
- cmake/FindSQLite3.cmake
Add FindSQLite3 from CMake v3.14 in cmake subdir custom CMake modules like FindSQLiteCpp
Add this cmake subdir to CMAKE_MODULE_PATH
Add a Travis CI build configuration using the libsqlite3-dev packagee from the Linux/Ubuntu distribution
> Fix linking with system library (libsqlite3)

- CMakeLists.txt
- appveyor.yml
- sqlite3/CMakeLists.txt
This PR adds support for an externally compiled SQLite3. There are two main changes:
1. Detect and use SQLite3 via cmake if requested by the user, and
2. Always link SQLiteCpp against cmake detected `Threads::Threads` and DL-libs.
The second change is a simplification and cleanup. SQLite3 always requires threads and DL-libraries. Therefore it seems not sensible to specify them individually for each target.
This PR also uses cmake standard functionality to detect the actual threads-implementation and DL-libraries for the current platform. This should improve portability to other (less common) platforms that may not use the name `pthreads` but another threading library name.
> Added support for external sqlite3

- include/SQLiteCpp/Statement.h
Splitted making a function pure from #242
> Efficiency - adding a pure attribute to getIndex()

- .github/workflows/build.yml
- .github/workflows/subdir_example.yml
- CMakeLists.txt
- examples/example2/CMakeLists.txt
- examples/example2/README.md
- examples/example2/build.bat
- examples/example2/build.sh
- examples/example2/src/main.cpp
Demonstrates how to use SQLiteCpp as a subdirectory (out of tree) of a CMake project.
See https://github.com/SRombauts/SQLiteCpp_Example
> Add an example2 based on SQLiteCpp_Example repository

- CMakeLists.txt
Several minor changes with respect to c++ standard:
* Changing `CMakeLists.txt` to make c++11 optional. This is a good idea because SQLiteCpp can support even older compilers. With this change, c++11 becomes requested but the build can proceed if it is not found.
* When tests are enabled, c++11 becomes mandatory. The user is informed about this setting via cmake output.
* Allow users to specify other c++ versions via the cmake options: `-DCMAKE_CXX_STANDARD="[98, 11, 14, 17, 20]"`
Its my understanding that this PR is more generic than https://github.com/SRombauts/SQLiteCpp/pull/239 because it allows users to manually specify a newer c++ standard, without all the special logic and extra options.
This PR may also supersede https://github.com/SRombauts/SQLiteCpp/pull/263 since it is more …
> CMakeLists.txt: Make c++11 optional unless building tests

- include/SQLiteCpp/Statement.h
- src/Statement.cpp
- tests/Statement_test.cpp
Hi,
we needed access to the declared type of a column for a SELECT statement, so I added a thin wrapper around the SQLite function sqlite3_column_decltype and a few tests. I hope, you also find this useful.
Best regards,
Daniel Schmidt
> Add a method on Statement to get the declared type of a column.

- cmake/SQLiteCppConfig.cmake.in
Without this, systems that linked against Threads::Threads (namely
Linux) don't "just work" with find_package(SQLiteCpp), but instead
require you to find & link against Threads manually.
So this fixes that by finiding it for you, if it was used.
> Add missing Threads dependency to Config.cmake.in

- src/Database.cpp
Adressing https://github.com/SRombauts/SQLiteCpp/issues/282 to add missing SQLITE_OPEN_FULLMUTEX flag in SQLite namespace.
> Add SQLITE_OPEN_FULLMUTEX flag

- CMakeLists.txt
Using the MinGW-W64 compiler on Windows results in a segfault when a database is initially opened. This seems to be the result of the `-fstack-protector` flag, which has patchy support in MinGW. 
Note some other major projects that have encountered this, and don't add this flag when compiling with MinGW on Windows:
https://github.com/bitcoin/bitcoin/issues/8732
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=86832
I can reproduce this with the example program and embedded sqlite3 library -- Building with MSVC works fine, and building with MinGW-W64 with the flag removed works fine, but segfaults at `sqlite3_open_v2()` with the flag added.
This PR adds a CMake option, `SQLITECPP_USE_STACK_PROTECTION`, defaulting to enabled, which allows disabling of this flag. Some other pull requests on this …
> Add CMake option to toggle stack protection

- CMakeLists.txt
- sqlite3/CMakeLists.txt
I added cmake option to enable json1 extension when building internal sqlite library.
I added the option under the SQLITECPP_INTERNAL_SQLITE `if` statement so it is clear that this option is only valid when building the internal sqlite library.
> Allow building of sqlite JSON1 extension when building internal sqlite library

- CMakeLists.txt
It was failing to compile since it wasn't linking against the sqlcipher
library if using the system libraries. This fix simply links the library
& includes the header path.
PkgConf is optional in this process, and it will fall back to regular
search for header & lib if it's not installed.
> Fix compilation if using SQLITE_HAS_CODEC

- include/SQLiteCpp/Database.h
I am really sorry, I have forgot to add OPEN_FULLMUTEX as extern into Database.h file. Is it possible to merge it into release 3.1.0?
> Add OPEN_FULLMUTEX flag into Database.h file

- CMakeLists.txt
This PR removes the explicit setting of the MSVC runtime from SQLiteCpp. This is because overriding the default runtime can have various negative implications. For example, the build of SQLiteCpp fails on MSVC 2019 with errors:
```
LINK : warning LNK4098: defaultlib 'MSVCRTD' conflicts with use of other libs; use /NODEFAULTLIB:library
LINK : warning LNK4217: symbol 'free' defined in 'libucrtd.lib(free.obj)' is imported by 'sqlite3.lib(sqlite3.c.obj)' in function 'vfsUnlink'
LINK : warning LNK4217: symbol 'malloc' defined in 'libucrtd.lib(malloc.obj)' is imported by 'sqlite3.lib(sqlite3.c.obj)' in function 'vfsUnlink'
LINK : warning LNK4217: symbol '__acrt_iob_func' defined in 'libucrtd.lib(_file.obj)' is imported by 'sqlite3.lib(sqlite3.c.obj)' in function 'sqlite3VdbePrintOp'
LINK : …
```
> Disable explicit setting of MSVC runtime

- src/Database.cpp
strncpy gives an "output may be truncated" warning in newer versions of
GCC due to *pBuf being larger (100) than *pHeaderStr (16).  Use memcpy
and explicitly null-terminate the target string.
This fixes issue #306.
> Fix build warning due to string truncation

- include/SQLiteCpp/Database.h
- src/Database.cpp
- tests/Database_test.cpp
Similar to Statement::tryExecuteStep(), allows calls to sqlite3_exec() with the caller assuming responsibility for checking and handling the returned status.
> Add Database::tryExec()

- CMakeLists.txt
Add a `SQLITECPP_INCLUDE_SCRIPT` option to support disabling the addition of config & script files to the library.
(The default is `ON`, replicating current behavior.)
Adds flexibility without requiring library users to modify the `CMakeLists.txt` directly.
Also, this is needed for a dependent program that automatically packages the library source (as a dependency) in a source tarball "snapshot" and wants to exclude files not needed for building via CMake locally (.git* and such) to save space and reduce the overall file count.
> [CMake] Add SQLITECPP_INCLUDE_SCRIPT option

- include/SQLiteCpp/Database.h
- tests/Database_test.cpp
Added an additional constructor in `Database.h` that accepts a `std::filesystem::path` object. Also updated the `ctorExecCreateDropExist` unit test in `Database_test.h` which will test the new constructor if the detected compiler supports c++17.
> Add Database constructor for filesystem::path #296

- sqlite3/CMakeLists.txt
When building with SQLITECPP_INTERNAL_SQLITE=ON the SQLite amalgamation
source is used for generating the library. Using one big source file
means all the library code will be put in a single section. When
building statically linked executables the entire section will be
linked even if a small portion of the library is actually used.
This commit addresses this issue by setting the -ffunction-sections
compiler option when building the library. As each function is placed in
a section of its own the linker, when passed the --gc-sections, will
throw away unused sections (functions) and reduce the executable size.
> Compile internal SQLite library with -ffunction-sections

- README.md
Removes manually adding the include directory from the Readme install instructions.
The manual step is not needed since the include dir is already added on the library target by the current CMake configuration: https://github.com/SRombauts/SQLiteCpp/blob/f6b32259f2d3733b645049b015152322ba4c2694/CMakeLists.txt#L299
> Fix Readme installation instructions

- CHANGELOG.md
- examples/example1/main.cpp
- include/SQLiteCpp/Database.h
- include/SQLiteCpp/Statement.h
- src/Database.cpp
- src/Statement.cpp
- tests/Column_test.cpp
- tests/Database_test.cpp
Fix #331 How to get the number of updated/deleted rows?
> Added Database and Statement method getChanges()

- include/SQLiteCpp/Database.h
- tests/Database_test.cpp
macOS flat out refuses to compile if you touch `std::filesystem::path` when targetting macOS < 10.15 (to be able to deploy a binary to older macOS versions) with the `-mmacosx-version-min=10.14` (or earlier) compiler flags.
If you try to compile code with `::path` (even if you don't actually call it) the Apple clang gods smite you with:
```
foo.cpp:8:26: error: 'path' is unavailable: introduced in macOS 10.15
std::filesystem::path p;
^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX11.3.sdk/usr/include/c++/v1/filesystem:738:24: note: 'path' has been explicitly marked unavailable here
class _LIBCPP_TYPE_VIS path {
^
```
This is reportedly caused by Apple's C++ team being somewhat incompetent at actually updating libc++ when they push out new …
> Disable std::filesystem on macOS when compiling C++17 but targetting <10.15

- include/SQLiteCpp/Transaction.h
- src/Transaction.cpp
- tests/Transaction_test.cpp
See https://sqlite.org/lang_transaction.html.
> Allow specifying transaction behaviors DEFERRED, IMMEDIATE, and EXCLUSIVE

- CMakeLists.txt
This issue addresses #336 
Pull request #337 added the `package.xml` configuration but did not install it :sweat_smile: 
#336 can be safely closed after this
> Install the package.xml file

- meson.build
- meson_options.txt
- subprojects/.gitignore
- subprojects/gtest.wrap
- subprojects/sqlite3.wrap
This PR adds basic meson support, at the moment it does not compile on windows, however managed it to compile on Arch Linux, when the Windows support is ready it should fix also #53,#280 and add maybe put it on wrapdb fixing #97.
> add basic meson support.

- include/SQLiteCpp/Column.h
- include/SQLiteCpp/Statement.h
- src/Column.cpp
- src/Statement.cpp
- tests/Column_test.cpp
- tests/Statement_test.cpp
As title says I refactored Statement and Columns with minimal changes to wrapper API.
List of all major changes:
(Macros are still needed for "operator long" in Columns but not in Statement binds methods. Fixed width ints should properly detect size of long function parameter)
> Refactoring of Statement and Column classes

- tests/Statement_test.cpp
long & long long APIs have been replaced by int32_t and int64_t types in #349 
TODO: we need to continue cleanup APIs to remove all long from the codebase before we can release a new version
> Fix Statement unit test using long

- include/SQLiteCpp/Database.h
associate to [issues/322](https://github.com/SRombauts/SQLiteCpp/issues/322)
> Add compatible definition for std::experimental::filesystem

- meson.build
- tests/Statement_test.cpp
this PR is an improvement of #352, managing to compile statically and run unit tests successfully on windows.
a summary of the changes in this PR:
- Meson file
- use c++14 on windows(due to an error with xstddef)
- add a preprocessor definition ('NON_AMBIGOUS_OVERLOAD') to use int instead of long to prevent ambiguous overload when compiling with clang++, it does not affect cmake and it only is enabled on meson
- Unit tests
-  tests/Statement_test.cpp -> use "int64_t"(supported on c++11) instead of "long long" to prevent ambiguous overload errors (tested both on Arch Linux & Windows w clang)
- tests/Statement_test.cpp -> check if NON_AMBIGOUS_OVERLOAD is defined and use int instead of long if is the case (to prevent ambiguous overload on windows)
the library still does not compile …
> Windows improved support (meson)

- CMakeLists.txt
The option SQLITECPP_USE_STATIC_RUNTIME is now only defined for MSVC and its default value is now dependent of SQLITECPP_BUILD_TESTS, so it's now OFF by default
> Don't link anymore with Visual Studio's static runtime by default

- src/Column.cpp
- tests/Column_test.cpp
If the database is in a different format (ie. UTF-16) the memory that sqlite3_column_blob() will point to by default will be the native (UTF-16) encoding. Calling sqlite3_column_bytes() will basically be a noop for a BLOB or a TEXT already in UTF-8. Otherwise it'll convert to TEXT w/UTF-8.
Run the 'basis' tests against both a UTF-8 and a UTF-16 database. Reset & rerun query between tests blocks to reset column types. Reorder a few getText()/getString() operations to ensure we test both ordering. Don't try to convert random blob to TEXT. Will fail encoding conversion.
Extracted from https://github.com/SRombauts/SQLiteCpp/pull/379 by @dougnazar
> Ensure that TEXT column is UTF-8 encoded before using sqlite3_column_blob()

- CMakeLists.txt
- include/SQLiteCpp/Database.h
- meson.build
- meson_options.txt
Add a switch to disable `std::filesystem` so it can be disabled if required on older compilers, this should let users that older compilers versions to disable it, solving #378 for meson and cmake, additionally checks in the source code if the header is found
- CMakeLists.txt: adds a new option that is disabled by default
- Database.h
-  adds an additional check for `<filesystem>` and `<experimental/filesystem>`
- checks for the previous switch and disables the support if enabled
- `meson.build`/`meson.options` adds the same option that disables `std::filesystem` support
I think this PR should be made on `3.2.1` or greater as is a new feature/enhancement itself and should come with the other planned project cleanups, please let me know if there is anything else required
> make std::filesystem optional

- meson.build
- meson_options.txt
as the name implies this PR adds the missing `SQLITECPP_USE_STACK_PROTECTOR` and `SQLITECPP_OMIT_LOAD_EXTENSION` that were available in CMake but not in meson additionally adds the special check for `MinGW-W64` in order to not enable it and show a warning instead, solving a possible issue on meson related to #382 and #74
> [meson] add missing compile options

- include/SQLiteCpp/Database.h
- tests/Database_test.cpp
- Do not compare the version number for external SQLite3 libraries
- Correct use of the __has_include macro to stop the preprocessor from complaining
> Fix preprocessor issues

- meson.build
- meson_options.txt
this PR makes checks if there is a bundled sqlite3 in OSX that does not support load extension and disables the support automatically
> note: line feeds were changed from CRLF to LF
- meson_options.txt
- changed `SQLITE_OMMIT_LOAD_EXTENSION` to `SQLITE_OMIT_LOAD_EXTENSION` (typo fix)
- meson. Build
- change the version to 3.2.1
- changed `SQLITECPP_USE_STACK_PROTECTOR` to `SQLITECPP_USE_STACK_PROTECTION` (typo fix)
- adds the `SQLITE_OMIT_LOAD_EXTENSION` option and enables it if running on MacOS with a bundled sqlite that does not supports it
on wrapdb this can be added as a patch as is only a change in the meson files and not the project itself
> edit: there is a list of other changes that can be seen on the wrapdb repo
> meson project changes based on wrap submission review

- src/Database.cpp
- src/Savepoint.cpp
- tests/Savepoint_test.cpp
Add release for savepoint after rollabck in destructor for deleting it form sqlite transaction stack.
> fix incorrect work of savepoint

- include/SQLiteCpp/Savepoint.h
- src/Savepoint.cpp
Rename Savepoint::rollback() to Savepoint::rollbackTo()
Fix Savepoint comments with more explanations instead of only copying Transaction
Fix file formatting to comply to our code style, mainly braces on their own lines
> Rename Savepoint RollbackTo() and fix class comments and formatting

- .github/workflows/build.yml
Fix #382 #74 disable SQLITECPP_USE_STACK_PROTECTION when running on MinGW
> Add Mingw GitHub actions

- README.md
- examples/example1/meson.build
- examples/example2/meson.build
- examples/meson.build
- meson.build
- subprojects/sqlitecpp.wrap
Draft for meson docs in the project readme an usage Guide, needs some cleanup and should come after #394 #391 so the examples and project work out of the box in OSX 11+ under meson
-  [x] add build and installation guide for meson
> note: once meson support is mature enough it should be possible to add it on wrapdb and add a proper guide in the future
> add meson usage guide

- meson.build
Fix include directory name so include files get installed. 
Flag library for installation on non-Windows platforms.
> Fix meson installation

- CMakeLists.txt
- meson.build
make simple corrections in both build systems (Meson/CMake)
- remove the use of `add_definitions` for `std::filesystem` support in CMake
- fix the definition of `SQLITE_HAS_CODEC` in Meson
> Lint corrections

- README.md
I've encountered the same problem with prepared statements and transactions as described in https://github.com/SRombauts/SQLiteCpp/issues/264, and I thought it would be good to resolve this (relatively) minor issue.
> Add documentation for prepared statements in transactions

- CMakeLists.txt
- meson.build
- meson_options.txt
- src/Statement.cpp
Add an option to disable `sqlite3_expanded_sql` that disables the internal use of it inside the method `Statement::getExpandedSQL` so it gives a warning when building SQLiteCpp, at runtime it will give an exception instead
this should fix #213
- CMakeLists.txt: add the `SQLITECPP_DISABLE_EXPANDED_SQL` option along with the define `SQLITECPP_DISABLE_EXPANDED_SQL`
- meson.build/meson.options: add the same  `SQLITECPP_DISABLE_EXPANDED_SQL`  that defines `SQLITECPP_DISABLE_EXPANDED_SQL`
- Statement.cpp
- give a warning at compile time if  `SQLITECPP_DISABLE_EXPANDED_SQL` is not defined when running the version of sqlite < 3.14.0
- give an exception when trying to run `Statement::getExpandedSQL` if compiled witouth support for `sqlite3_expanded_sql`
> add disable option for sqlite3_expanded_sql

- examples/example2/meson.build
change the name to be `SQLITECPP_sample_demo2` instead of `SQLITECPP_sample_demo1`
> correct executable name in meson

- .github/workflows/build.yml
- .github/workflows/subdir_example.yml
There is a warning due to the usage of checkout@V2 that can be fixed by using V3 instead.
> use checkout@v3 in CMake CI

- include/SQLiteCpp/SQLiteCppExport.h
- meson.build
- src/Column.cpp
- src/Database.cpp
fixed several warnings that come from #406, most of the warnings are not harmful but it is better to fix them
- removed the  `#pragma message` inside `SQLiteCppExport.h`  as it showed as a warning
- removed `SQLITECPP_API` inside cpp files as it will be ignored and show a warning instead
- [meson only] check if stack protection is supported before adding the flag for it
this should fix #412
> Fix compiler warnings warning

- CMakeLists.txt
* So that users of the SQLiteCpp lib have it defined automatically
* Fixed #432
> Define SQLITECPP_COMPILE_DLL as PUBLIC

- CMakeLists.txt
Update cmake_minimum_required() to VERSION 3.5
Fix CMake 3.27 deprecation warning:
Compatibility with CMake < 3.5 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
> Update CMake minimum version to 3.5 to get rid of a new deprecation warning with CMake 3.27

- .github/workflows/build.yml
- improve readability of logs with better name and single line of script per "run:" step
- improve readability of the script itself with less "name: " and additional spaces around varnames
> Cleanup of the Github "build" workflow

- CMakeLists.txt
- Replace the set() of "/MT" to REPLACE "/MD" "/MT" inspired from Zlib licensed glfw https://github.com/glfw/glfw/blob/master/CMakeLists.txt
- Don't set SQLITECPP_USE_STATIC_RUNTIME by default when building with unit tests. Use gtest_force_shared_crt to force googletest to link against the default dynamic C++ runtime
Relates to #417
> Update usage of SQLITECPP_USE_STATIC_RUNTIME

- CMakeLists.txt
- sqlite3/CMakeLists.txt
BUILD_SHARED_LIBS is a standard CMake variable, but we declare it explicitly to make it prominent
> Declare BUILD_SHARED_LIBS option for discoverability

- meson.build
- subprojects/gtest.wrap
- subprojects/sqlite3.wrap
- subprojects/sqlitecpp.wrap
this PR only affects meson, however a later change could be made for CMake
updates the following depenencies:
- GTests to 1.14.0
- sqlite to 3.42.0
makes 
sets the recommended version to C++14 as Gtest now requires C++14, additionally shows a warning and sets it to c++14 if
- C++11 is set and is on windows (this was #354 but now checks if is C++11 and shows a warning instead of setting it to C++14 so it does not revert when using a newer version)
- C++11 is set and uses [GTest 1.14.0](https://github.com/google/googletest/releases/tag/v1.14.0) or greater,  for more information check [Google's Foundational C++ Support Policy](https://opensource.google/documentation/policies/cplusplus-support)
> [Meson] update meson dependencies

- .github/workflows/meson.yml
fixes a CI issue in OSX due to [PEP-668](https://peps.python.org/pep-0668/)
pip3 was used to install meson and ninja build, pipx is a drop in replacement for this use case.
> Macos ci fix

- examples/example1/meson.build
- examples/example2/meson.build
- meson.build
- subprojects/gtest.wrap
- subprojects/sqlite3.wrap
makes the following changes
- update meson wrap dependencies
- update gtest 1.14.0 -> 1.15.0
- update sqlite 3.42.0 -> 3.46.1
- removed redundant variables that pointed to the same sources in example executables
> Update meson dependencies [Meson only]

- include/SQLiteCpp/Statement.h
Rvalues are inherently unsuitable for no-copy binding, because their lifetime cannot be guaranteed. Separately declare, and delete, all overloads of bindNoCopy() that take a std::string rvalue.
> Explicitly =delete; Statement::bindNoCopy(..., std::string&&)

- CMakeLists.txt
find_package(PythonInterp) has been deprecated since cmake 3.5 and is throwing a warning as of 3.27 (maybe earlier).  Since the minimum required version is 3.5 for this repo, added a branch to use the appropriate find_package depending on the version.
Tested with 3.27 (above the split) and 3.10.x (below the split).  Both were successful for me (ubuntu:18.04 & 22.04).
> Add logic to use different FindPackage for python if cmake is above 3.12

- tests/Database_test.cpp
Without the change `gcc` detects unexpected tokens as:
/build/source/tests/Database_test.cpp:566:9: warning: extra tokens at end of #endif directive [8;;https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wendif-labels-Wendif-labels8;;]
566 | #endif  && !defined(__APPLE__)
|         ^~
> tests/Database_test.cpp: fix a warning around `#endif`

- include/SQLiteCpp/Statement.h
Without the change the build fails on `gcc-15` as:
[  5%] Building CXX object CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o
In file included from /build/source/include/SQLiteCpp/Column.h:14,
from /build/source/include/SQLiteCpp/Database.h:14,
from /build/source/include/SQLiteCpp/Backup.h:15,
from /build/source/src/Backup.cpp:12:
/build/source/include/SQLiteCpp/Statement.h:132:39: error: 'uint32_t' does not name a type
132 |     void bind(const int aIndex, const uint32_t      aValue);
|                                       ^~~~~~~~
/build/source/include/SQLiteCpp/Statement.h:20:1: note: 'uint32_t' is defined in header '<cstdint>'; this is probably fixable by adding '#include <cstdint>'
19 | #include <memory>
+++ |+#include <cstdint>
20 |
> SQLiteCpp/Statement.h: add missing `<cstdint>` include

- meson.build
- subprojects/sqlite3.wrap
- updates fallback gtest to 1.15.2
- updates fallback sqlite3 to 3.49.2
- adds additional checks of the default c++ standard version if GTest is >= 1.17.0
- bumps the version to 3.3.3
> update meson dependencies

- CHANGELOG.md
- CMakeLists.txt
- Doxyfile
- include/SQLiteCpp/SQLiteCpp.h
- package.xml
* Update SQLite from 3.46.1 to 3.49.2 (2025-05-07) by @SRombauts in https://github.com/SRombauts/SQLiteCpp/pull/505
* Add a Github Dependabot config file by @SRombauts in https://github.com/SRombauts/SQLiteCpp/pull/480
* Bump actions/checkout from 3 to 4 by @dependabot in https://github.com/SRombauts/SQLiteCpp/pull/482
* Replace all double-quoted string literals by single quotes in unit test by @SRombauts in https://github.com/SRombauts/SQLiteCpp/pull/483
* Use explicit versions of Ubuntu images instead of latest by @SRombauts in https://github.com/SRombauts/SQLiteCpp/pull/484
* Test linking with builtin libsqlite3-dev package on Ubuntu by @SRombauts in https://github.com/SRombauts/SQLiteCpp/pull/485
* Add logic to use different FindPackage for python if cmake is above 3.12 by …
> Release 3.3.3

- include/SQLiteCpp/Database.h
In some cases a non existing define is being undefined. This fixes this case.
SQLITECPP_HAVE_EXPERIMENTAL_FILESYSTEM => SQLITECPP_HAVE_STD_EXPERIMENTAL_FILESYSTEM
> fix: faulty undef

- CMakeLists.txt
Currently, every project pulling in SQLiteCpp automatically gets an `make install` which installs SQLiteCpp into the system. This is often not desired, since other projects only statically link. The solution is to add another "SQLITECPP_INSTALL" option, which allows to turn on/off this behavior.
> fix: hide installation behind an option
